export enum ButtonEnum {
  ALIGN = 'align',
  AUDIO = 'audio',
  BLOCKQUOTE = 'blockquote',
  BOLD = 'bold',
  CODE_VIEW = 'codeView',
  FONT = 'font',
  FONT_COLOR = 'fontColor',
  FONT_SIZE = 'fontSize',
  FORMAT_BLOCK = 'formatBlock',
  FULL_SCREEN = 'fullScreen',
  GALLERY = 'gallery',
  HILITE_COLOR = 'hiliteColor',
  HORIZONTAL_RULE = 'horizontalRule',
  IMAGE = 'image',
  INDENT = 'indent',
  ITALIC = 'italic',
  LINE_BREAK = '/',
  LINE_HEIGHT = 'lineHeight',
  LINK = 'link',
  LIST = 'list',
  OUTDENT = 'outdent',
  PARAGRAPH_STYLE = 'paragraphStyle',
  PREVIEW = 'preview',
  PRINT = 'print',
  REDO = 'redo',
  REMOVE_FORMAT = 'removeFormat',
  SAVE = 'save',
  SHOW_BLOCKS = 'showBlocks',
  SLASH = '/',
  STRIKE = 'strike',
  SUBSCRIPT = 'subscript',
  SUPERSCRIPT = 'superscript',
  TABLE = 'table',
  TEMPLATE = 'template',
  TEXT_STYLE = 'textStyle',
  UNDERLINE = 'underline',
  UNDO = 'undo',
  VIDEO = 'video',
}

export enum LangEnum {
  CKB = 'ckb',
  DA = 'da',
  DE = 'de',
  EN = 'en',
  ES = 'es',
  FR = 'fr',
  HE = 'he',
  IT = 'it',
  JA = 'ja',
  KO = 'ko',
  LV = 'lv',
  NL = 'nl',
  PL = 'pl',
  PT_BR = 'pt_br',
  RO = 'ro',
  RU = 'ru',
  SE = 'se',
  UA = 'ua',
  ZH_CN = 'zh_cn',
  ZH_TW = 'zh_tw',
}

export enum UploadStateEnum {
  CREATE = 'create',
  DELETE = 'delete',
  UPDATE = 'update',
}

export enum PluginDisplayEnum {
  COMMAND = 'command',
  CONTAINER = 'container',
  DIALOG = 'dialog',
  SUBMENU = 'submenu',
}
